
const tableDate = () => {
  return {
    dataSource: [
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
      {
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },{
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },{
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },{
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },{
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },{
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },{
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },{
        date: '5月1号',
        region: '安徽',
        effectiveRegisterNum:'1',
        phoneAuthNum:'2',
        decisionCompletionNum:"3",
        decisionPassNum:'4',
        withdrawNum:'5',
        withdrawPassNum:'6',
        phoneReviewNum:'7',
        phoneReviewPassNum:'8',
        signMoney:'9',
        decisionCompletionRate:'10%',
        decisionPassRate:'20%',
        withdrawRate:'30%'

      },
    ],
    columns: [
      {
        title: '日期',
        dataIndex: 'date',
        key: 'date',
        visiable:true,
      },
      {
        title: '身份验证数',
        dataIndex: 'region',
        key: 'region',
        visiable:true,
      },
      {
        title: '手机实名',
        dataIndex: 'effectiveRegisterNum',
        key: 'effectiveRegisterNum',
        visiable:true,
      },
      {
        title: '交单总数(申请阶段)',
        dataIndex: 'phoneAuthNum',
        key: 'phoneAuthNum',
        visiable:true,
      },
      {
        title: '截流人数(申请阶段)',
        dataIndex: 'decisionCompletionNum',
        key: 'decisionCompletionNum',
        visiable:true,
      },
      {
        title: '转化人数(申请阶段)',
        dataIndex: 'decisionPassNum',
        key: 'decisionPassNum',
        visiable:true,
      },
      {
        title: '预审人数',
        dataIndex: 'withdrawNum',
        key: 'withdrawNum',
        visiable:true,
      },
      {
        title: '预审拒绝人数',
        dataIndex: 'withdrawPassNum',
        key: 'withdrawPassNum',
        visiable:true,
      },
      {
        title: '预审通过人数',
        dataIndex: 'phoneReviewNum',
        key: 'phoneReviewNum',
        visiable:true,
      },
      {
        title: '电审通过人数',
        dataIndex: 'phoneReviewPassNum',
        key: 'phoneReviewPassNum',
        visiable:true,
      },
      {
        title: '授信完成人数',
        dataIndex: 'signMoney',
        key: 'signMoney',
        visiable:true,
      },
      {
        title: '授信通过人数',
        dataIndex: 'decisionCompletionRate',
        key: 'decisionCompletionRate',
        visiable:true,
      },
      {
        title: '授信金额',
        dataIndex: 'decisionPassRate',
        key: 'decisionPassRate',
        visiable:true,
      },
      {
        title: '交单总数(提现阶段)',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '截流人数(提现阶段)',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '可电审总量',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '进件总数',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '电审通过量',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '电审通过金额',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '电审拒绝量',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '签约人数',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '签约金额',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '签约通过人数',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '签约通过金额',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '放款人数',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '放款金额',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '新用户贷款人数',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '新用户贷款金额',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '老用户贷款金额',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
      {
        title: '老用户贷款人数',
        dataIndex: 'withdrawRate',
        key: 'withdrawRate',
        visiable:true,
      },
    ]
  }
}

module.exports = {
  tableDate
}
